# Interpolation Methods

## LinearNDInterpolator from scipy

This has replaced the use of interp2d.  The advice is now to use a different sent of interpolation functions - see https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html.

The **RegularGridInterpolator** (or **RGI**) is an alternative which is useful for the general use case I'm expecting.  Other functions can accept unstructred data, but are slower due to additional processing.

The RGI accepts data where the axes are monotonically increasing, but the spacing does not have to be even.


In [4]:
# Import the required libraries
import numpy as np
from scipy.interpolate import RegularGridInterpolator

# Define the grid points (x and y)
#x = np.linspace(0, 4, 5)  # x-axis grid: [0, 1, 2, 3, 4]
#y = np.linspace(0, 4, 5)  # y-axis grid: [0, 1, 2, 3, 4]

# Create the 2D grid of data (Z)
#X, Y = np.meshgrid(x, y, indexing='ij')
#Z = X**2 + Y**2  # Example function: z = x^2 + y^2

# Provide the data
x = [0, 1, 2, 3, 4]
y = [0, 2, 3, 4, 5]

Z = np.array([[1, 1.1, 1.2, 1.3, 1.4],
              [2, 2.1, 2.2, 2.3, 2.4],
              [3, 3.1, 3.2, 3.3, 3.4],
              [4, 4.1, 4.2, 4.3, 4.4],
              [5, 5.1, 5.2, 5.3, 5.4]])

# Define the x & y values where you want to interpolate the data
xi = 1
yi = 1

# Print the data to the command window
print(' ')
print('x is: ', x)
print('y is: ', y)
print(' ')
print('Z is: ', Z)

# You need to create an interpolator object, in this case called RGI
RGI = RegularGridInterpolator((x, y), Z, method='linear', bounds_error=False, fill_value=None)

# Now use the object to interpolate the data - the points can be input as a tuple, list or numpy array
values = RGI((xi, yi))

# Output the interpolated values
print(' ')
print('Interpolated value: ', values)


 
x is:  [0, 1, 2, 3, 4]
y is:  [0, 2, 3, 4, 5]
 
Z is:  [[1.  1.1 1.2 1.3 1.4]
 [2.  2.1 2.2 2.3 2.4]
 [3.  3.1 3.2 3.3 3.4]
 [4.  4.1 4.2 4.3 4.4]
 [5.  5.1 5.2 5.3 5.4]]
 
Interpolated value:  2.05
